# Generated by Django 2.0.2 on 2018-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('enum', 'enum')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
