# Generated by Django 2.0.2 on 2018-02-07 05:16

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180206_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='type',
            field=enumfields.fields.EnumField(enum=api.models.FieldTypeValues, max_length=10),
        ),
    ]
