# Generated by Django 2.0.2 on 2018-02-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180207_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeEnumValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_value', models.CharField(max_length=100)),
                ('field_associated_with_enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Field')),
            ],
        ),
    ]
