# Generated by Django 2.0.2 on 2018-02-07 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fieldtypeenumvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
