# Generated by Django 2.0.2 on 2018-02-09 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180207_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypeenumvalues',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypeenumvalues',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='fields',
            field=models.ManyToManyField(blank=True, to='api.Field'),
        ),
    ]
